spring.application.name=api-service

spring.datasource.url=jdbc:postgresql://localhost:5433/flowforge
spring.datasource.username=flowforge
spring.datasource.password=flowforge

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
